In [56]:
import pandas as pd
import numpy as np
import utils
%reload_ext autoreload
%autoreload 2

df_raw = utils.extract("by_civil_status.xls", skip_rows=2)
df_raw

,YEAR,Single,Married,Widower,Separated,Divorced,Not Reported,TOTAL
0,1988,31989.0,23530.0,2133.0,134.0,143.0,91,58020.0
1,1989,30338.0,23203.0,1858.0,98.0,143.0,105,55745.0
2,1990,33477.0,27005.0,2299.0,127.0,194.0,47,63149.0
3,1991,31989.0,27559.0,2517.0,186.0,192.0,21,62464.0
4,1992,33759.0,27976.0,2123.0,131.0,159.0,6,64154.0
5,1993,33589.0,29987.0,2432.0,148.0,234.0,NaN,66390.0
6,1994,32760.0,28911.0,2491.0,149.0,220.0,NaN,64531.0
7,1995,29663.0,24439.0,1818.0,158.0,163.0,1,56242.0
8,1996,29747.0,28399.0,2393.0,182.0,192.0,NaN,60913.0
9,1997,24990.0,26287.0,2341.0,172.0,269.0,NaN,54059.0
10,1998,18569.0,18795.0,1415.0,103.0,127.0,NaN,39009.0
11,1999,19451.0,19081.0,1661.0,135.0,179.0,NaN,40507.0
12,2000,25438.0,23583.0,1657.0,154.0,179.0,20,51031.0
13,2001,24721.0,24959.0,1916.0,233.0,219.0,6,52054.0
14,2002,28118.0,27100.0,2015.0,179.0,306.0,2,57720.0
15,2003,26687.0,26233.0,1804.0,172.0,239.0,2,55137.0
16,2004,32870.0,29577.0,1946.0,208.0,323.0,,64924.0
17,2005,34346.0,32056.0,2035.0,239.0,347.0,5,69028.0
18,2006,40505.0,39007.0,2616.0,303.0,536.0,,82967.0
19,2007,40200.0,36128.0,3295.0,318.0,656.0,2,80599.0
20,2008,35250.0,32390.0,2341.0,264.0,538.0,17,70800.0
21,2009,41119.0,34700.0,2874.0,347.0,581.0,97,79718.0
22,2010,47143.0,35564.0,2359.0,380.0,609.0,20,86075.0
23,2011,44825.0,35214.0,2439.0,338.0,579.0,15,83410.0
24,2012,43908.0,35776.0,2866.0,401.0,675.0,14,83640.0
25,2013,41388.0,33164.0,2639.0,368.0,623.0,46,78228.0
26,2014,45280.0,32062.0,2307.0,345.0,657.0,38,80689.0
27,2015,52957.0,36238.0,2671.0,350.0,754.0,28,92998.0
28,2016,50236.0,35592.0,2436.0,305.0,703.0,82,89354.0
29,2017,46211.0,30646.0,1813.0,329.0,658.0,122,79779.0
30,2018,40668.0,30069.0,1998.0,277.0,614.0,93,73719.0
31,2019,36804.0,25563.0,1799.0,261.0,680.0,57,65164.0
32,2020,8513.0,6607.0,349.0,70.0,118.0,46,15703.0
33,TOTAL,1137508.0,947400.0,71656.0,7564.0,12809.0,983,2177920.0
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Source: Commission on Filipinos Overseas (CFO),NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [152]:
df_clean = utils.pivot(df_raw)

df_clean["COUNT"] = df_clean["COUNT"].astype(str).str.strip().replace([""], np.nan)
df_clean = df_clean.fillna(0)
df_clean["COUNT"] = df_clean["COUNT"].astype(float).astype(int)
df_clean.loc[df_clean["YEAR"] == "2006"]

     YEAR      CATEGORY  COUNT
18   2006        Single  40505
53   2006       Married  39007
88   2006       Widower   2616
123  2006     Separated    303
158  2006      Divorced    536
193  2006  Not Reported      0