In [1]:
import os
import sys
import pandas as pd
import numpy as np
sys.path.append(os.path.abspath(".."))
import scripts.utils as utils
%reload_ext autoreload
%autoreload 2

df_raw_age_group = utils.extract("by_age_group.xls")
df_raw_age_group

,AGE GROUP,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL,%
0,14 - Below,9588.0,9100.0,8433.0,8199.0,9154.0,10524.0,12407.0,13271.0,12207.0,...,17170.0,18014.0,21581.0,20430.0,18741.0,15820.0,13323.0,3109.0,531007.0,0.211075
1,15 - 19,4712.0,4650.0,4498.0,4359.0,4822.0,5520.0,5941.0,6237.0,5620.0,...,8309.0,8401.0,11102.0,10500.0,9319.0,8233.0,6454.0,1512.0,263064.0,0.104568
2,20 - 24,5846.0,5956.0,5164.0,5035.0,5196.0,5512.0,5733.0,5440.0,5735.0,...,8029.0,8396.0,8902.0,8127.0,7216.0,6673.0,5791.0,1394.0,261928.0,0.104116
3,25 - 29,5919.0,6643.0,5323.0,5348.0,5489.0,5809.0,6946.0,6899.0,7076.0,...,8060.0,8790.0,9178.0,9134.0,7957.0,7809.0,7592.0,2180.0,297729.0,0.118347
4,30 - 34,4048.0,5357.0,3659.0,3956.0,4264.0,4836.0,6359.0,6561.0,6731.0,...,8546.0,9284.0,10238.0,10579.0,9690.0,9276.0,9108.0,2360.0,281312.0,0.111821
5,35 - 39,2445.0,3488.0,2409.0,2695.0,2845.0,3179.0,4069.0,4379.0,4265.0,...,6677.0,7323.0,8700.0,8821.0,8179.0,7223.0,6790.0,1741.0,203711.0,0.080975
6,40 - 44,1799.0,2760.0,1678.0,1703.0,1665.0,1855.0,2334.0,2770.0,2746.0,...,4990.0,5159.0,5901.0,5795.0,5364.0,4827.0,4428.0,1110.0,140005.0,0.055652
7,45 - 49,1543.0,2145.0,1437.0,1586.0,1613.0,1590.0,1742.0,1981.0,1897.0,...,3342.0,3534.0,4248.0,4204.0,3597.0,3346.0,2949.0,602.0,104351.0,0.041479
8,50 - 54,2142.0,2402.0,1679.0,1601.0,1800.0,1840.0,1943.0,1970.0,1973.0,...,2979.0,3081.0,3291.0,3215.0,2739.0,2639.0,2278.0,446.0,94110.0,0.037409
9,55 - 59,2955.0,2985.0,2364.0,2007.0,2344.0,2339.0,2436.0,2384.0,2095.0,...,3159.0,2870.0,3182.0,2717.0,2399.0,2530.0,2071.0,425.0,98672.0,0.039222
10,60 - 64,3068.0,3223.0,2461.0,2109.0,2458.0,2576.0,2554.0,2389.0,2022.0,...,2804.0,2496.0,2710.0,2345.0,1871.0,2172.0,1757.0,337.0,96264.0,0.038265
11,65 - 69,2653.0,2630.0,1737.0,1497.0,1809.0,1867.0,1990.0,1848.0,1602.0,...,2184.0,1786.0,2061.0,1809.0,1393.0,1585.0,1384.0,261.0,73570.0,0.029244
12,70 - Above,2149.0,2614.0,1639.0,1456.0,1810.0,1891.0,1896.0,1867.0,1762.0,...,1978.0,1555.0,1902.0,1677.0,1309.0,1516.0,1233.0,217.0,69602.0,0.027667
13,Not Reported /,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,No Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,14.0,...,1.0,NaN,2.0,1.0,5.0,70.0,6.0,9.0,404.0,0.000161
15,T O T A L,48867.0,53953.0,42481.0,41551.0,45269.0,49338.0,56350.0,58020.0,55745.0,...,78228.0,80689.0,92998.0,89354.0,79779.0,73719.0,65164.0,15703.0,2515729.0,1.000000
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Source: Commission on Filipinos Overseas (CFO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
# clean age table
df_clean_age_group = utils.clean(df_raw_age_group)
row_mapping = {
    "Not Reported /": "Not Reported",
    "No Response": "Not Reported"
}

df_clean_age_group["AGE GROUP"] = df_clean_age_group["AGE GROUP"].replace(row_mapping)
df_clean_age_group = df_clean_age_group.groupby("AGE GROUP", as_index=False).sum()
df_clean_age_group

,AGE GROUP,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL,%
0,14 - Below,9588,9100,8433,8199,9154,10524,12407,13271,12207,...,17170,18014,21581,20430,18741,15820,13323,3109,531007.0,0.211075
1,15 - 19,4712,4650,4498,4359,4822,5520,5941,6237,5620,...,8309,8401,11102,10500,9319,8233,6454,1512,263064.0,0.104568
2,20 - 24,5846,5956,5164,5035,5196,5512,5733,5440,5735,...,8029,8396,8902,8127,7216,6673,5791,1394,261928.0,0.104116
3,25 - 29,5919,6643,5323,5348,5489,5809,6946,6899,7076,...,8060,8790,9178,9134,7957,7809,7592,2180,297729.0,0.118347
4,30 - 34,4048,5357,3659,3956,4264,4836,6359,6561,6731,...,8546,9284,10238,10579,9690,9276,9108,2360,281312.0,0.111821
5,35 - 39,2445,3488,2409,2695,2845,3179,4069,4379,4265,...,6677,7323,8700,8821,8179,7223,6790,1741,203711.0,0.080975
6,40 - 44,1799,2760,1678,1703,1665,1855,2334,2770,2746,...,4990,5159,5901,5795,5364,4827,4428,1110,140005.0,0.055652
7,45 - 49,1543,2145,1437,1586,1613,1590,1742,1981,1897,...,3342,3534,4248,4204,3597,3346,2949,602,104351.0,0.041479
8,50 - 54,2142,2402,1679,1601,1800,1840,1943,1970,1973,...,2979,3081,3291,3215,2739,2639,2278,446,94110.0,0.037409
9,55 - 59,2955,2985,2364,2007,2344,2339,2436,2384,2095,...,3159,2870,3182,2717,2399,2530,2071,425,98672.0,0.039222
10,60 - 64,3068,3223,2461,2109,2458,2576,2554,2389,2022,...,2804,2496,2710,2345,1871,2172,1757,337,96264.0,0.038265
11,65 - 69,2653,2630,1737,1497,1809,1867,1990,1848,1602,...,2184,1786,2061,1809,1393,1585,1384,261,73570.0,0.029244
12,70 - Above,2149,2614,1639,1456,1810,1891,1896,1867,1762,...,1978,1555,1902,1677,1309,1516,1233,217,69602.0,0.027667
13,Not Reported,0,0,0,0,0,0,0,24,14,...,1,0,2,1,5,70,6,9,404.0,0.000161

In [3]:
# build dimension table
unique_age_group = (
    df_clean_age_group[["AGE GROUP"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

unique_age_group["Age_ID"] = [f"PH_AGE_{i+1:03d}" for i in unique_age_group.index]
dim_ph_age = unique_age_group[["Age_ID", "AGE GROUP"]].rename(columns={"AGE GROUP": "Age_Group"})

dim_ph_age

        Age_ID     Age_Group
0   PH_AGE_001    14 - Below
1   PH_AGE_002       15 - 19
2   PH_AGE_003       20 - 24
3   PH_AGE_004       25 - 29
4   PH_AGE_005       30 - 34
5   PH_AGE_006       35 - 39
6   PH_AGE_007       40 - 44
7   PH_AGE_008       45 - 49
8   PH_AGE_009       50 - 54
9   PH_AGE_010       55 - 59
10  PH_AGE_011       60 - 64
11  PH_AGE_012       65 - 69
12  PH_AGE_013    70 - Above
13  PH_AGE_014  Not Reported

In [4]:
# build fact table

fact_age_prep = df_clean_age_group.merge(
    dim_ph_age, left_on="AGE GROUP", right_on="Age_Group", how="left"
)

years_cols = [col for col in df_clean_age_group.columns if col not in ["AGE GROUP", "%", "TOTAL"]]
fact_ph_age = pd.melt(
    fact_age_prep,
    id_vars=["Age_ID"],
    value_vars=years_cols,
    var_name="Year",
    value_name="Emigrant_Count"
)

fact_ph_age

         Age_ID  Year  Emigrant_Count
0    PH_AGE_001  1981            9588
1    PH_AGE_002  1981            4712
2    PH_AGE_003  1981            5846
3    PH_AGE_004  1981            5919
4    PH_AGE_005  1981            4048
..          ...   ...             ...
555  PH_AGE_010  2020             425
556  PH_AGE_011  2020             337
557  PH_AGE_012  2020             261
558  PH_AGE_013  2020             217
559  PH_AGE_014  2020               9

[560 rows x 3 columns]

In [5]:
utils.load(dim_ph_age, "dim_ph_age.csv")
utils.load(fact_ph_age, "fact_ph_age.csv")

downloaded csv file dim_ph_age.csv
downloaded csv file fact_ph_age.csv